name: workflow_01
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3
      - name: Checkout additional private repository
        uses: actions/checkout@v3
        with:
          repository: daniela-git/repo2
          token: ${{ secrets.ACTIONS_TOKEN }}
          path: ./qa-tools
      - name: list
        run: ls
      - name: run repo 1
        working-directory: test
        run: node repo1.js
      - name: run repo 2
        working-directory: qa-tools/src
        run: node test.js
