name: emulators
on:
  workflow_dispatch:

jobs:
  Run_test:
    runs-on: macos-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3
      - name: Install appium
        run: |
          npm install -g appium
          appium -v
          appium driver install uiautomator2
      - name: Install packages repo
        run: npm install
      - name: list
        run: ls
      - name: Run appium server
        run: |
          nohup appium server \
            --port=4723 \
            --base-path=/wd/hub \
            --relaxed-security \
            --log-no-colors \
            --log-timestamp \
            2>&1 > "appium.log" &
      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          script: npm run wdio:android
          avd-name: emulator
          api-level: 33
          arch: x86_64
          target: google_apis
      - name: upload video
        env:
          TOKEN: ${{ secrets.TOKEN }}
        if: failure()
        run: npm run uploadVideo
