name: workflow_01
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Test
        run: |
          curl -X POST https://api.github.com/repos/daniela-git/repo2/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACTIONS_TOKEN }} \
          --data '{"event_type": "trigger_repo2", "client_payload": { "login":"android","pass":"android pass"}}'\
          > /dev/null

          # Get the workflow_id of the triggered run
          workflow_id=$(curl -X GET \
            -H "Authorization: Bearer ${{ secrets.ACTIONS_TOKEN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/daniela-git/repo2/actions/runs?event=repository_dispatch \
            | jq -r '.workflow_runs[0].id')

          echo $workflow_id

          # Wait for the triggered workflow to complete
          while true; do
            status=$(curl -X GET \
              -H "Authorization: Bearer ${{ secrets.ACTIONS_TOKEN }}" \
              -H "Accept: application/vnd.github.everest-preview+json" \
              https://api.github.com/repos/daniela-git/repo2/actions/runs?workflow_id=$workflow_id \
              | jq -r '.workflow_runs[0].conclusion')
            echo $status
            if [ "$status" == "success" ] || [ "$status" == "failure" ]; then
              break
            fi
            sleep 10
          done
          # Perform additional actions or return a response to repo 1
          if [ "$status" == "success" ]; then
            echo "Repo 2 workflow succeeded!"
          else
            echo "Repo 2 workflow failed!"
          fi.,mnbvnoiytas   Zx
