name: workflow_01
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Test
        run: |
          workflow_id = $(curl -X POST https://api.github.com/repos/daniela-git/repo2/actions/workflows/repository-dispatch.yml/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACTIONS_TOKEN }} \
          --data '{"event_type": "Trigger Workflow", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'", "ios": {"login":"ios","pass":"ios pass"},"android":{"login":"android","pass":"android pass"}}}')

          echo $workflow_id
